source "https://supermarket.chef.io"

metadata

cookbook 'selinux', '~> 0.9.0'
cookbook 'mysql', '~> 7.0.0'
cookbook 'mysql2_chef_gem', '~> 1.1.0'
cookbook 'database', '~> 5.1.2'
cookbook 'docker', '~> 2.7.1'
cookbook 'poise-python', '~> 1.3.0'
